### ISSUE TITLE
不够色情

### ISSUE THREAD

**Issue by xiaozhang-up** [freeze-dolphin/tentacle_gallery_storage#1]
这哪够啊
快多来几十个

**Comment by freeze-dolphin** [comment]
我不是给你了baidu网盘链接了吗，你自己不下载，怪我咯
![I3SXL38{@(} L``W%YOI01S](https://user-images.githubusercontent.com/40729044/130076367-3cfde88d-edeb-4dee-850b-945d50955ad0.jpg)
